"""Evaluation routines for HW3.

Evaluation modes
----------------
clean
    Standard CIFAR-10 test set accuracy (10 000 images).

corrupted
    CIFAR-10-C: 19 corruption types × 5 severity levels.  Reports per-type
    accuracy and mean corruption accuracy (mCA).  The CIFAR-10-C dataset
    must be downloaded separately and placed under ``config.data.cifar10c_dir``.
    Download: https://zenodo.org/record/2535967

adversarial_linf
    PGD20 attack with L-infinity norm (ε = 4/255) applied to the CIFAR-10
    test set.

adversarial_l2
    PGD20 attack with L2 norm (ε = 0.25) applied to the CIFAR-10 test set.

transferability
    Adversarial examples generated by a teacher model (L-inf, ε = 4/255)
    evaluated on a student model.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from torchvision import datasets

from attacks import pgd_attack
from parameters import Config
from train import CIFAR10_CLASSES, get_val_transforms

logger = logging.getLogger("cs515")

# CIFAR-10-C corruption types (19 total)
CORRUPTIONS = [
    "brightness", "contrast", "defocus_blur", "elastic_transform",
    "fog", "frost", "gaussian_blur", "gaussian_noise", "glass_blur",
    "impulse_noise", "jpeg_compression", "motion_blur", "pixelate",
    "saturate", "shot_noise", "snow", "spatter", "speckle_noise", "zoom_blur",
]


def _normalized_input_bounds(
    config: Config,
    device: torch.device,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Return valid per-channel bounds for normalized CIFAR-10 tensors."""
    mean = torch.tensor(config.data.mean, device=device).view(1, 3, 1, 1)
    std = torch.tensor(config.data.std, device=device).view(1, 3, 1, 1)
    return (0.0 - mean) / std, (1.0 - mean) / std


def _linf_attack_budget_in_normalized_space(
    config: Config,
    device: torch.device,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Map raw-pixel L-inf epsilon and step-size into normalized tensor space."""
    std = torch.tensor(config.data.std, device=device).view(1, 3, 1, 1)
    eps = torch.full((1, 3, 1, 1), config.attack.pgd_eps_linf, device=device) / std
    step_size = torch.full((1, 3, 1, 1), config.attack.pgd_step_size_linf, device=device) / std
    return eps, step_size


# ─────────────────────────────────────────────────────────────────────────────
# Test data loader (clean CIFAR-10)
# ─────────────────────────────────────────────────────────────────────────────

def get_test_loader(config: Config) -> DataLoader:
    """Create the CIFAR-10 clean test DataLoader.

    Args:
        config: Full experiment configuration.

    Returns:
        DataLoader for the official CIFAR-10 test split (10 000 images).
    """
    transform = get_val_transforms(config)
    test_dataset = datasets.CIFAR10(
        root=config.data.data_dir,
        train=False,
        download=True,
        transform=transform,
    )
    return DataLoader(
        test_dataset,
        batch_size=config.train.batch_size,
        shuffle=False,
        num_workers=config.data.num_workers,
        pin_memory=config.data.pin_memory,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Confusion matrix helpers
# ─────────────────────────────────────────────────────────────────────────────

def initialize_confusion_matrix(num_classes: int) -> List[List[int]]:
    """Initialise a square confusion matrix filled with zeros.

    Args:
        num_classes: Number of classification classes.

    Returns:
        Nested list of shape (num_classes, num_classes).
    """
    return [[0] * num_classes for _ in range(num_classes)]


def update_confusion_matrix(
    confusion_matrix: List[List[int]],
    targets: torch.Tensor,
    predictions: torch.Tensor,
) -> None:
    """Update a confusion matrix in-place for one batch.

    Args:
        confusion_matrix: Existing confusion matrix (modified in-place).
        targets: Ground-truth labels tensor.
        predictions: Predicted labels tensor.
    """
    for true_label, pred_label in zip(targets.tolist(), predictions.tolist()):
        confusion_matrix[true_label][pred_label] += 1


def compute_per_class_accuracy(confusion_matrix: List[List[int]]) -> List[float]:
    """Compute per-class accuracy from the confusion matrix.

    Args:
        confusion_matrix: Square confusion matrix.

    Returns:
        List of per-class accuracies.
    """
    per_class: List[float] = []
    for class_idx, row in enumerate(confusion_matrix):
        correct = row[class_idx]
        total = sum(row)
        per_class.append(correct / total if total > 0 else 0.0)
    return per_class


# ─────────────────────────────────────────────────────────────────────────────
# FLOPs counting
# ─────────────────────────────────────────────────────────────────────────────

def count_flops(
    model: nn.Module,
    input_res: Tuple[int, int, int],
) -> Optional[Tuple[str, str]]:
    """Count MACs and parameters using ``ptflops``.

    Args:
        model: PyTorch model to profile.
        input_res: Input resolution as (C, H, W).

    Returns:
        Tuple of (macs_string, params_string), or ``None`` if ptflops is absent.
    """
    try:
        from ptflops import get_model_complexity_info  # type: ignore[import]
    except ImportError:
        logger.warning("ptflops not installed — skipping FLOPs count.")
        return None

    macs, params = get_model_complexity_info(
        model, input_res, as_strings=True,
        print_per_layer_stat=False, verbose=False,
    )
    return macs, params


# ─────────────────────────────────────────────────────────────────────────────
# Results persistence
# ─────────────────────────────────────────────────────────────────────────────

def save_results(results: Dict[str, Any], config: Config, suffix: str = "") -> None:
    """Save evaluation results as JSON next to the checkpoint.

    Args:
        results: Dictionary containing evaluation outputs.
        config: Full experiment configuration.
        suffix: Optional suffix appended to the filename (e.g. ``"_corrupted"``).
    """
    save_path = Path(config.run.save_path)
    save_path.parent.mkdir(parents=True, exist_ok=True)
    fname = f"{config.run.experiment_name}_test_results{suffix}.json"
    results_path = save_path.parent / fname

    with results_path.open("w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=2)

    logger.info("Results saved → %s", results_path)


# ─────────────────────────────────────────────────────────────────────────────
# Clean CIFAR-10 evaluation
# ─────────────────────────────────────────────────────────────────────────────

@torch.no_grad()
def run_test(
    model: nn.Module,
    config: Config,
    device: torch.device,
) -> Dict[str, Any]:
    """Evaluate the model on the official CIFAR-10 test set.

    Args:
        model: Model to evaluate (checkpoint already loaded).
        config: Full experiment configuration.
        device: Target device.

    Returns:
        Dictionary containing test metrics.
    """
    test_loader = get_test_loader(config)
    criterion = nn.CrossEntropyLoss()
    num_classes = config.data.num_classes
    confusion_matrix = initialize_confusion_matrix(num_classes)

    running_loss = 0.0
    total_correct = 0
    total_samples = 0

    model.eval()
    logger.info("Evaluating on clean CIFAR-10 test set (%d samples)...",
                len(test_loader.dataset))

    for images, labels in test_loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        logits = model(images)
        loss = criterion(logits, labels)
        predictions = torch.argmax(logits, dim=1)

        batch_size = images.size(0)
        running_loss += loss.item() * batch_size
        total_correct += (predictions == labels).sum().item()
        total_samples += batch_size

        update_confusion_matrix(confusion_matrix, labels.cpu(), predictions.cpu())

    test_loss = running_loss / total_samples
    test_accuracy = total_correct / total_samples
    per_class_accuracy = compute_per_class_accuracy(confusion_matrix)

    flops_result = count_flops(model, (3, 32, 32))

    results: Dict[str, Any] = {
        "eval_mode": "clean",
        "test_loss": test_loss,
        "test_accuracy": test_accuracy,
        "num_samples": total_samples,
        "per_class_accuracy": per_class_accuracy,
        "confusion_matrix": confusion_matrix,
        "flops": flops_result[0] if flops_result else "N/A",
        "params": flops_result[1] if flops_result else "N/A",
    }

    save_results(results, config, suffix="")

    logger.info("=" * 70)
    logger.info("Clean Test Results  [%s]", config.run.experiment_name)
    logger.info("=" * 70)
    logger.info("Test loss        : %.4f", test_loss)
    logger.info("Overall accuracy : %.4f  (%d / %d)",
                test_accuracy, total_correct, total_samples)
    if flops_result:
        logger.info("MACs             : %s", flops_result[0])
        logger.info("Parameters       : %s", flops_result[1])
    logger.info("-" * 70)
    logger.info("Per-class accuracy:")
    for class_idx, acc in enumerate(per_class_accuracy):
        class_correct = confusion_matrix[class_idx][class_idx]
        class_total = sum(confusion_matrix[class_idx])
        logger.info("  %-12s : %.4f  (%d / %d)",
                    CIFAR10_CLASSES[class_idx], acc, class_correct, class_total)
    logger.info("=" * 70)

    return results


# ─────────────────────────────────────────────────────────────────────────────
# CIFAR-10-C evaluation
# ─────────────────────────────────────────────────────────────────────────────

def _load_cifar10c_corruption(
    cifar10c_dir: str,
    corruption: str,
    severity: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """Load images and labels for one corruption type at one severity level.

    The CIFAR-10-C files are organised as NumPy arrays:
    - ``{corruption}.npy``: shape (50 000, 32, 32, 3), where the first
      10 000 images are severity 1, the next 10 000 are severity 2, etc.
    - ``labels.npy``: shape (50 000,), identical labels repeated for all
      five severity levels.

    Args:
        cifar10c_dir: Directory containing the CIFAR-10-C .npy files.
        corruption: Corruption name (e.g., ``"gaussian_noise"``).
        severity: Severity level (1–5).

    Returns:
        Tuple of (images array (N, 32, 32, 3) uint8, labels array (N,) int64).

    Raises:
        FileNotFoundError: If the corruption file does not exist.
    """
    data_path = Path(cifar10c_dir) / f"{corruption}.npy"
    labels_path = Path(cifar10c_dir) / "labels.npy"

    if not data_path.exists():
        raise FileNotFoundError(
            f"CIFAR-10-C file not found: {data_path}\n"
            "Download from: https://zenodo.org/record/2535967\n"
            f"Expected directory: {cifar10c_dir}"
        )
    if not labels_path.exists():
        raise FileNotFoundError(f"CIFAR-10-C labels not found: {labels_path}")

    # Each severity block is 10 000 images
    start = (severity - 1) * 10_000
    end = severity * 10_000

    images = np.load(data_path)[start:end]      # (10000, 32, 32, 3) uint8
    labels = np.load(labels_path)[start:end]    # (10000,) int64

    return images, labels


def _cifar10c_loader(
    images: np.ndarray,
    labels: np.ndarray,
    config: Config,
) -> DataLoader:
    """Build a DataLoader from CIFAR-10-C NumPy arrays.

    Args:
        images: Uint8 images array, shape (N, 32, 32, 3).
        labels: Integer labels array, shape (N,).
        config: Full experiment configuration (for batch size / num_workers).

    Returns:
        DataLoader that yields normalised image tensors.
    """
    import torchvision.transforms.functional as TF

    mean = torch.tensor(config.data.mean)
    std = torch.tensor(config.data.std)

    # Convert (N, H, W, C) uint8 → (N, C, H, W) float normalised
    imgs_tensor = torch.from_numpy(images).float() / 255.0   # (N, H, W, C)
    imgs_tensor = imgs_tensor.permute(0, 3, 1, 2)             # (N, C, H, W)
    imgs_tensor = (imgs_tensor - mean[None, :, None, None]) / std[None, :, None, None]

    labels_tensor = torch.from_numpy(labels.astype(np.int64))

    dataset = TensorDataset(imgs_tensor, labels_tensor)
    return DataLoader(
        dataset,
        batch_size=config.train.batch_size,
        shuffle=False,
        num_workers=0,  # TensorDataset doesn't benefit from workers
    )


@torch.no_grad()
def run_test_corrupted(
    model: nn.Module,
    config: Config,
    device: torch.device,
) -> Dict[str, Any]:
    """Evaluate the model on CIFAR-10-C across all corruption types and severities.

    Reports accuracy for each (corruption, severity) pair and computes the
    mean corruption accuracy (mCA) averaged over all 19 × 5 = 95 conditions.

    Args:
        model: Model to evaluate.
        config: Full experiment configuration.
        device: Target device.

    Returns:
        Dictionary containing per-corruption-severity accuracy and mCA.
    """
    model.eval()
    cifar10c_dir = config.data.cifar10c_dir

    logger.info("Evaluating on CIFAR-10-C (19 corruptions × 5 severities)...")
    logger.info("CIFAR-10-C directory: %s", cifar10c_dir)

    corruption_results: Dict[str, Dict[str, float]] = {}
    all_accs: List[float] = []

    for corruption in CORRUPTIONS:
        sev_accs: Dict[str, float] = {}
        for severity in range(1, 6):
            try:
                images, labels = _load_cifar10c_corruption(
                    cifar10c_dir, corruption, severity
                )
            except FileNotFoundError as err:
                logger.warning("Skipping %s (sev=%d): %s", corruption, severity, err)
                continue

            loader = _cifar10c_loader(images, labels, config)

            correct = 0
            total = 0
            for imgs, lbls in loader:
                imgs = imgs.to(device, non_blocking=True)
                lbls = lbls.to(device, non_blocking=True)
                preds = model(imgs).argmax(dim=1)
                correct += (preds == lbls).sum().item()
                total += lbls.size(0)

            acc = correct / total if total > 0 else 0.0
            sev_accs[f"severity_{severity}"] = acc
            all_accs.append(acc)

        corruption_results[corruption] = sev_accs
        mean_sev = sum(sev_accs.values()) / len(sev_accs) if sev_accs else 0.0
        logger.info("  %-20s  mean_acc=%.4f", corruption, mean_sev)

    mca = sum(all_accs) / len(all_accs) if all_accs else 0.0

    results: Dict[str, Any] = {
        "eval_mode": "corrupted",
        "mean_corruption_accuracy": mca,
        "per_corruption": corruption_results,
        "num_conditions": len(all_accs),
    }

    save_results(results, config, suffix="_corrupted")

    logger.info("=" * 70)
    logger.info("CIFAR-10-C Results  [%s]", config.run.experiment_name)
    logger.info("=" * 70)
    logger.info("Mean Corruption Accuracy (mCA) : %.4f", mca)
    logger.info("=" * 70)

    return results


# ─────────────────────────────────────────────────────────────────────────────
# Adversarial (PGD) evaluation
# ─────────────────────────────────────────────────────────────────────────────

def run_test_adversarial(
    model: nn.Module,
    config: Config,
    device: torch.device,
    norm: str,
) -> Dict[str, Any]:
    """Evaluate the model under PGD adversarial attack.

    Processes the entire CIFAR-10 test set (10 000 images) batch by batch,
    generating adversarial examples and measuring accuracy.

    Args:
        model: Model to attack and evaluate.
        config: Full experiment configuration (attack params from
                ``config.attack``).
        device: Target device.
        norm: Threat model — ``"linf"`` or ``"l2"``.

    Returns:
        Dictionary containing clean and adversarial accuracy,
        and lists of misclassified sample tensors for Grad-CAM / T-SNE.
    """
    assert norm in ("linf", "l2"), f"Unknown norm: {norm!r}"
    clamp_min, clamp_max = _normalized_input_bounds(config, device)

    if norm == "linf":
        eps = config.attack.pgd_eps_linf
        step_size = config.attack.pgd_step_size_linf
        attack_eps, attack_step_size = _linf_attack_budget_in_normalized_space(config, device)
        label = f"PGD{config.attack.pgd_steps}-Linf (ε={eps:.4f})"
        suffix = "_adversarial_linf"
    else:
        eps = config.attack.pgd_eps_l2
        step_size = config.attack.pgd_step_size_l2
        attack_eps = eps
        attack_step_size = step_size
        label = f"PGD{config.attack.pgd_steps}-L2 (ε={eps:.4f})"
        suffix = "_adversarial_l2"

    test_loader = get_test_loader(config)
    model.eval()

    logger.info("Running adversarial evaluation: %s", label)

    clean_correct = 0
    adv_correct = 0
    total_samples = 0

    # Collect misclassified adversarial samples for Grad-CAM / T-SNE
    misclassified_clean: List[torch.Tensor] = []
    misclassified_adv: List[torch.Tensor] = []
    misclassified_true: List[int] = []
    misclassified_clean_pred: List[int] = []
    misclassified_adv_pred: List[int] = []

    for images, labels in test_loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        # Clean predictions
        with torch.no_grad():
            clean_preds = model(images).argmax(dim=1)
            clean_correct += (clean_preds == labels).sum().item()

        # Generate adversarial examples
        adv_images = pgd_attack(
            model=model,
            images=images,
            labels=labels,
            norm=norm,
            eps=attack_eps,
            step_size=attack_step_size,
            steps=config.attack.pgd_steps,
            random_start=config.attack.pgd_random_start,
            clamp_min=clamp_min,
            clamp_max=clamp_max,
        )

        with torch.no_grad():
            adv_preds = model(adv_images).argmax(dim=1)
            adv_correct += (adv_preds == labels).sum().item()

        total_samples += labels.size(0)

        # Collect samples where clean is correct but adversarial is wrong
        if len(misclassified_clean) < config.attack.num_gradcam_samples:
            mask = (clean_preds == labels) & (adv_preds != labels)
            for idx in mask.nonzero(as_tuple=True)[0]:
                if len(misclassified_clean) >= config.attack.num_gradcam_samples:
                    break
                misclassified_clean.append(images[idx].cpu())
                misclassified_adv.append(adv_images[idx].cpu())
                misclassified_true.append(labels[idx].item())
                misclassified_clean_pred.append(clean_preds[idx].item())
                misclassified_adv_pred.append(adv_preds[idx].item())

    clean_acc = clean_correct / total_samples
    adv_acc = adv_correct / total_samples

    results: Dict[str, Any] = {
        "eval_mode": f"adversarial_{norm}",
        "attack_label": label,
        "norm": norm,
        "eps": eps,
        "step_size": step_size,
        "pgd_steps": config.attack.pgd_steps,
        "clean_accuracy": clean_acc,
        "adversarial_accuracy": adv_acc,
        "num_samples": total_samples,
        "misclassified_indices": {
            "true_labels": misclassified_true,
            "clean_preds": misclassified_clean_pred,
            "adv_preds": misclassified_adv_pred,
        },
    }

    save_results(results, config, suffix=suffix)

    logger.info("=" * 70)
    logger.info("Adversarial Results  [%s]  %s", config.run.experiment_name, label)
    logger.info("=" * 70)
    logger.info("Clean accuracy      : %.4f", clean_acc)
    logger.info("Adversarial accuracy: %.4f  (drop = %.4f)",
                adv_acc, clean_acc - adv_acc)
    logger.info("=" * 70)

    # Attach collected tensors for Grad-CAM / T-SNE (not JSON-serialised)
    results["_misclassified_clean"] = misclassified_clean
    results["_misclassified_adv"] = misclassified_adv

    return results


# ─────────────────────────────────────────────────────────────────────────────
# Adversarial transferability evaluation
# ─────────────────────────────────────────────────────────────────────────────

def run_test_transferability(
    teacher_model: nn.Module,
    student_model: nn.Module,
    config: Config,
    device: torch.device,
) -> Dict[str, Any]:
    """Test adversarial transferability from teacher to student.

    Generates PGD20 L-infinity adversarial examples using the teacher model
    and evaluates them on the student model without any re-generation.

    Args:
        teacher_model: Model used to generate adversarial examples.
        student_model: Model on which the transferred examples are evaluated.
        config: Full experiment configuration.
        device: Target device.

    Returns:
        Dictionary containing teacher and student adversarial accuracy.
    """
    eps = config.attack.pgd_eps_linf
    step_size = config.attack.pgd_step_size_linf
    steps = config.attack.pgd_steps
    attack_eps, attack_step_size = _linf_attack_budget_in_normalized_space(config, device)
    clamp_min, clamp_max = _normalized_input_bounds(config, device)

    logger.info(
        "Adversarial transferability: PGD%d-Linf (ε=%.4f) teacher → student",
        steps, eps,
    )

    test_loader = get_test_loader(config)
    teacher_model.eval()
    student_model.eval()

    teacher_adv_correct = 0
    student_adv_correct = 0
    total_samples = 0

    for images, labels in test_loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        # Generate adversarial examples w.r.t. the teacher
        adv_images = pgd_attack(
            model=teacher_model,
            images=images,
            labels=labels,
            norm="linf",
            eps=attack_eps,
            step_size=attack_step_size,
            steps=steps,
            random_start=config.attack.pgd_random_start,
            clamp_min=clamp_min,
            clamp_max=clamp_max,
        )

        with torch.no_grad():
            teacher_preds = teacher_model(adv_images).argmax(dim=1)
            student_preds = student_model(adv_images).argmax(dim=1)

        teacher_adv_correct += (teacher_preds == labels).sum().item()
        student_adv_correct += (student_preds == labels).sum().item()
        total_samples += labels.size(0)

    teacher_adv_acc = teacher_adv_correct / total_samples
    student_adv_acc = student_adv_correct / total_samples

    results: Dict[str, Any] = {
        "eval_mode": "transferability",
        "eps_linf": eps,
        "pgd_steps": steps,
        "teacher_adversarial_accuracy": teacher_adv_acc,
        "student_adversarial_accuracy": student_adv_acc,
        "num_samples": total_samples,
    }

    save_results(results, config, suffix="_transferability")

    logger.info("=" * 70)
    logger.info("Transferability Results  [%s]", config.run.experiment_name)
    logger.info("=" * 70)
    logger.info("Teacher adv accuracy : %.4f  (white-box)", teacher_adv_acc)
    logger.info("Student adv accuracy : %.4f  (black-box transfer)", student_adv_acc)
    logger.info("Transfer success rate: %.4f",
                1.0 - student_adv_acc)
    logger.info("=" * 70)

    return results
